#!/bin/sh
set -e

MAX_RETRIES=30
RETRY_INTERVAL=5
ADDRESSES_FILE="./src/contractAddresses.json"

echo "Waiting for contract addresses to be available at $ADDRESSES_FILE"

# Wait for contract addresses file to exist
retry_count=0
while [ ! -f "$ADDRESSES_FILE" ] && [ $retry_count -lt $MAX_RETRIES ]; do
  echo "Waiting for contract addresses file to be created ($((retry_count+1))/$MAX_RETRIES)..."
  sleep $RETRY_INTERVAL
  retry_count=$((retry_count+1))
done

# Check if file exists after waiting
if [ ! -f "$ADDRESSES_FILE" ]; then
  echo "Error: Contract addresses file not created after waiting. Building with placeholder."
  # Create a placeholder file to allow build to continue
  mkdir -p $(dirname "$ADDRESSES_FILE")
  echo '{"EWasteTracker":"0x0000000000000000000000000000000000000000","EWasteCertificate":"0x0000000000000000000000000000000000000000"}' > "$ADDRESSES_FILE"
  exit 0
fi

# Check content of file
if grep -q "0x" "$ADDRESSES_FILE"; then
  echo "✅ Contract addresses file found with valid content"
  cat "$ADDRESSES_FILE"
else
  echo "⚠️ Contract addresses file exists but may not have valid content:"
  cat "$ADDRESSES_FILE"
fi

# Create or update the timestamp file
TIMESTAMP_FILE="./src/deployment-timestamp.js"
# Use a simpler date format to avoid compatibility issues
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "// This file is automatically generated to force cache refreshes" > "$TIMESTAMP_FILE"
echo "export const DEPLOYMENT_TIMESTAMP = \"$TIMESTAMP\";" >> "$TIMESTAMP_FILE"
echo "export const CONTRACT_ADDRESSES = $(cat $ADDRESSES_FILE);" >> "$TIMESTAMP_FILE"

echo "✅ Created/updated timestamp file at: $TIMESTAMP_FILE"
echo "🕒 Timestamp: $TIMESTAMP"

exit 0 