const fs = require('fs');
const path = require('path');

async function main() {
  console.log("\n🔄 Resetting frontend after contract deployment...");
  
  try {
    // Read the contract addresses
    const frontendDir = path.join(__dirname, "..", "frontend", "src");
    const addressesPath = path.join(frontendDir, "contractAddresses.json");
    
    if (!fs.existsSync(addressesPath)) {
      throw new Error("Contract addresses file not found. Did you run deploy.js first?");
    }
    
    const addressesData = fs.readFileSync(addressesPath);
    const addresses = JSON.parse(addressesData);
    
    console.log(`\n📄 Found contract addresses:`);
    console.log(`🔹 EWasteTracker: ${addresses.EWasteTracker}`);
    console.log(`🔹 EWasteCertificate: ${addresses.EWasteCertificate}`);
    
    // Create a timestamp file to force cache refresh
    const timestampPath = path.join(frontendDir, "deployment-timestamp.js");
    const timestamp = new Date().toISOString();
    
    fs.writeFileSync(
      timestampPath,
      `// This file is automatically generated to force cache refreshes\n` +
      `export const DEPLOYMENT_TIMESTAMP = "${timestamp}";\n` +
      `export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};\n`
    );
    
    console.log(`\n✅ Created/updated timestamp file at: ${timestampPath}`);
    console.log(`🕒 Timestamp: ${timestamp}`);
    
    // Update the index.js or App.js to import this timestamp (if not already importing)
    const indexJsPath = path.join(frontendDir, "index.js");
    if (fs.existsSync(indexJsPath)) {
      let indexContent = fs.readFileSync(indexJsPath, 'utf8');
      
      // Only add the import if it doesn't exist
      if (!indexContent.includes('deployment-timestamp')) {
        // Find the last import statement
        const lastImportIndex = indexContent.lastIndexOf('import');
        const lastImportEnd = indexContent.indexOf(';', lastImportIndex);
        
        if (lastImportIndex !== -1 && lastImportEnd !== -1) {
          const beforeImport = indexContent.substring(0, lastImportEnd + 1);
          const afterImport = indexContent.substring(lastImportEnd + 1);
          
          const newImport = `\n// Import deployment timestamp to force cache refresh\nimport './deployment-timestamp';\n`;
          
          // Update the file with the new import
          indexContent = beforeImport + newImport + afterImport;
          fs.writeFileSync(indexJsPath, indexContent);
          
          console.log(`✅ Updated ${indexJsPath} with timestamp import`);
        } else {
          console.log(`⚠️ Could not automatically update ${indexJsPath}. Please add manually:`);
          console.log(`   import './deployment-timestamp';`);
        }
      } else {
        console.log(`✅ Timestamp import already exists in ${indexJsPath}`);
      }
    }
    
    console.log("\n🔍 Checking for AuthContext.js to update...");
    const authContextPath = path.join(frontendDir, "context", "AuthContext.js");

    if (fs.existsSync(authContextPath)) {
      let authContent = fs.readFileSync(authContextPath, 'utf8');
      
      // Look for both possible imports
      const importLine1 = `import contractAddresses from '../contractAddresses.json';`;
      const importLine2 = `import { CONTRACT_ADDRESSES } from '../deployment-timestamp';`;
      
      // Only update if it's using the direct JSON import
      if (authContent.includes(importLine1) && !authContent.includes(importLine2)) {
        // Replace the direct import with the timestamp import
        authContent = authContent.replace(
          importLine1, 
          `import { CONTRACT_ADDRESSES } from '../deployment-timestamp';`
        );
        
        // Replace references to contractAddresses with CONTRACT_ADDRESSES
        authContent = authContent.replace(/contractAddresses\./g, 'CONTRACT_ADDRESSES.');
        
        fs.writeFileSync(authContextPath, authContent);
        console.log(`✅ Updated AuthContext.js to use timestamp-based imports`);
      } else if (authContent.includes(importLine2)) {
        console.log(`✅ AuthContext.js is already using timestamp-based imports`);
      } else {
        console.log(`⚠️ Could not find expected import pattern in AuthContext.js`);
        console.log(`   Please manually update to import from './deployment-timestamp'`);
      }
    }
    
    console.log("\n✨ Frontend reset completed!");
    console.log("\n🔴 IMPORTANT: You need to restart your frontend application for changes to take effect!");
    console.log("   Run these commands:");
    console.log("   cd frontend");
    console.log("   npm run build");
    console.log("   npm run start");
    
  } catch (error) {
    console.error(`\n❌ Error resetting frontend: ${error.message}`);
    if (error.stack) console.error(error.stack);
    process.exit(1);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Error:", error);
    process.exit(1);
  }); 